name = "NanoDates"
uuid = "46f1a544-deae-4307-8689-c12aa3c955c6"
keywords = ["Julia", "Dates", "time", "date", "nanoseconds"]
license = "MIT"
authors = ["Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"]
description = "NanoDate is a nanosecond resolved DateTime type" 
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[compat]
Aqua = "0.5, 0.6, 0.7, 0.8"
julia = "1.7"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "Dates"]

